import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Login from "./components/login/login";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { getServerSession } from "next-auth";
import Header from "./components/header/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Project",
  description: "Generated by create next app",
  icons:{
    icon:'/logo.png'
  }
};

export default async function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
      </body>
    </html>
  );
}
